sudo: required
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_ed5a7d88e2ff_key -iv $encrypted_ed5a7d88e2ff_iv
  -in ci-testing-44aa72dccf32.json.enc -out ci-testing-44aa72dccf32.json -d
- docker build -t sergeypixoneye/learning_ci -f Dockerfile.dev .
script:
- docker run sergeypixoneye/learning_ci npm run test -- --coverage
deploy:
  provider: gae
  keyfile: "./ci-testing-44aa72dccf32.json.enc"
  project: ci-testing-217212
